name: Publish

on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: protocol-implementation/Kotlin

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Clean Java
      run: ./gradlew clean
    - name: Build Java
      run: ./gradlew build
    - name: Release
      working-directory: embedded-serial-protocol
      run: |
        version="$(./utilities/version/get_version.sh)"
        gh release create "$version" protocol-implementation/Kotlin/serial-protocol/build/libs/*.jar --title "$version" --generate-notes --repo https://github.com/warrenwoolseyiii/embedded-serial-protocol --target git-packages
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}