name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Clean Java
      run: ./gradlew clean
      working-directory: protocol-implementation/Kotlin
    - name: Build Java
      run: ./gradlew build
      working-directory: protocol-implementation/Kotlin
    - name: Release Java
      run: |
        version="$(./utilities/version/get_version.sh)"
        gh release create "$version" protocol-implementation/Kotlin/serial-protocol/build/libs/*.jar --title "$version" --generate-notes --repo https://github.com/warrenwoolseyiii/embedded-serial-protocol --target pypi-publish-workflow
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      working-directory: protocol-implementation/Kotlin
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean Python
      run: |
        rm -rf dist
        mkdir dist
      working-directory: protocol-implementation/Python
    - name: Build Python
      run: |
        python3 -m pip install --upgrade build
        python3 -m build
        python3 -m pip install --upgrade twine
      working-directory: protocol-implementation/Python
    - name: Publish Python
      run:
        python3 -m twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
      working-directory: protocol-implementation/Python

